sudo: required
services:
  - docker


before_install:
  - docker build -t arvind412/docker-react -f Dockerfile.dev .


script:
  - docker run arvind412/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-251043900428"
  bucket_path: "docker"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$aws_SECRET_KEY"
